<meta charset="UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="renderer" content="webkit">
<meta name="description" content="YoFoon's 个人博客">
<meta name="keywords" content="个人博客,react学习,YoFoon,自适应">
<meta name="author" content="YoFoon,yofoon@qq.com">
<meta name="robots" content="all">
<meta name="viewport" content="initial-scale=1, maximum-scale=3, minimum-scale=1, user-scalable=no">
<link rel="shortcut icon" type="image/x-icon" href="/dist/images/icon.ico" media="screen">